### ISSUE TITLE
First round of graduating nodes from `node-nursery`

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#155]
Candidates:

- `createVectorDatabase` -- stays put
- `addToVectorDatabase` -- stays put
- `queryVectorDatabase` -- stays put
- `embedDocs` -- stays put
- [ ] `embedString` -- graduates as `embedText` to `LLM Starter Kit`
- `cache` -- stays put
- `textAsset` -- stays put
- `textAssetsFromPath` -- stays put
- `vars` -- remove
- `localMemory` -- remove
- [ ] `validateJson` -- graduates to `JSON Kit` (see #154)
- [ ] `schemish` -- graduates to `JSON Kit` (see #154)
- `templateParser` -- stays put
- [ ] `map` -- graduates to `Ops Kit` (see #127)
- [ ] `batcher` -- graduates to `Ops Kit` (see #127)
- [ ] `chunker` -- graduates to `LLM Starter Kit`.

**Comment by dglazkov** [comment]
Conversely, we could turn the LLM Starter Kit into a "Breadboard Starter Kit" and just put all of the graduating nodes into it.

Cons: less organization, everything is in one kit
Pros: easy to reach for, fewer publishing logistics (one vs. many)
